# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/papertrader
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# App
spring.application.name=papertrader
server.port=8082

# Load secrets
spring.config.import=optional:classpath:application-secrets.properties